### ISSUE TITLE
If I use Glowstone with open source Minecraft client in offline mode, do I still have to follow the EULA?

### ISSUE THREAD

**Issue by mio-19** [GlowstoneMC/docs#3]
([Discord](https://discord.gg/TFJqhsC) doesn't work on FirefoxESR on Debian 10(only shows blank))
Here are serval basically working open source clients for Minecraft:
https://github.com/iceiix/stevenarella
https://github.com/Thinkofname/steven-go

**Comment by mastercoms** [comment]
For a safe answer, no.
For a real answer, get a lawyer and ask them.

I'm sorry, but I can't be more helpful than that. These involve very complex legal topics, and as a programmer, I have no say in this area.

**Comment by gdude2002** [comment]
> (Discord doesn't work on FirefoxESR on Debian 10(only shows blank))

Just to let you know that Discord's desktop client should work fine on Debian 10 (installed via snap, flatpak, or the official `.deb`) as well as the web client working an up-to-date browser (be that Firefox, Chrome, or otherwise). FF ESR is going to be rather out of date, being an extended support release. The current version of Firefox is `72.0.2` and the ESR could be as far back as `60.x`.

As our project lead has said, though, we really can't help you with legal questions relating to the Mojang EULA. Questioning them directly will not help you either - you will have to ask a lawyer.
